//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Models.Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class kiralama
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kiralama()
        {
            this.kullanıcı = new HashSet<kullanıcı>();
        }
    
        public int kira_ID { get; set; }
        public Nullable<int> arac_ID { get; set; }
        public Nullable<int> musteri_ID { get; set; }
        public Nullable<System.DateTime> kiralanmaTarihi { get; set; }
        public Nullable<double> kiraUcret { get; set; }
        public Nullable<double> verilişKM { get; set; }
        public Nullable<double> sonKM { get; set; }
    
        public virtual araçBilgisi araçBilgisi { get; set; }
        public virtual müşteri müşteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kullanıcı> kullanıcı { get; set; }
    }
}
