//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Models.Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanıcı
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kullanıcı()
        {
            this.şirket = new HashSet<şirket>();
        }
    
        public int kullanici_ID { get; set; }
        public Nullable<int> arac_ID { get; set; }
        public Nullable<int> rezervasyon_ID { get; set; }
        public Nullable<int> kiralama_ID { get; set; }
        public Nullable<int> musteri_ID { get; set; }
    
        public virtual araçBilgisi araçBilgisi { get; set; }
        public virtual kiralama kiralama { get; set; }
        public virtual müşteri müşteri { get; set; }
        public virtual rezervasyon rezervasyon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<şirket> şirket { get; set; }
    }
}
