//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Models.Veritabani
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AracKiralamaEntities : DbContext
    {
        public AracKiralamaEntities()
            : base("name=AracKiralamaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<araçBilgisi> araçBilgisi { get; set; }
        public virtual DbSet<kiralama> kiralama { get; set; }
        public virtual DbSet<kullanıcı> kullanıcı { get; set; }
        public virtual DbSet<müşteri> müşteri { get; set; }
        public virtual DbSet<rezervasyon> rezervasyon { get; set; }
        public virtual DbSet<şirket> şirket { get; set; }
    }
}
