//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Models.Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class müşteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public müşteri()
        {
            this.kiralama = new HashSet<kiralama>();
            this.kullanıcı = new HashSet<kullanıcı>();
            this.rezervasyon = new HashSet<rezervasyon>();
        }
    
        public int musteri_ID { get; set; }
        public string musteriAd { get; set; }
        public string musteriSoyad { get; set; }
        public Nullable<int> musteriTC { get; set; }
        public Nullable<System.DateTime> musteriDogumTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kiralama> kiralama { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kullanıcı> kullanıcı { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rezervasyon> rezervasyon { get; set; }
    }
}
