//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Models.Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class şirket
    {
        public int sirket_ID { get; set; }
        public Nullable<int> kullanici_ID { get; set; }
    
        public virtual kullanıcı kullanıcı { get; set; }
    }
}
